
USE killTeamList;
GO

ALTER TABLE Armies WITH CHECK
ADD CONSTRAINT FK_FactionID FOREIGN KEY(FactionID) REFERENCES Factions(FactionID)
ON UPDATE CASCADE
GO

ALTER TABLE Armies WITH CHECK
ADD CONSTRAINT FK_CommanderID FOREIGN KEY(CommanderID) REFERENCES Commanders(ID)
ON UPDATE CASCADE

ALTER TABLE Armies WITH CHECK
ADD CONSTRAINT FK_TroopID FOREIGN KEY(TroopID) REFERENCES Troops(TroopID)
ON UPDATE CASCADE
GO
ALTER TABLE Armies WITH CHECK
ADD CONSTRAINT FK_PlayerID FOREIGN KEY(PlayerID) REFERENCES Players(PlayerID)
ON UPDATE CASCADE

GO
ALTER TABLE Troops WITH CHECK
ADD CONSTRAINT FK_AbilityID FOREIGN KEY(AbilityID) REFERENCES SpecialistAbilities(ID)
ON UPDATE CASCADE

GO
ALTER TABLE NarrativeCampaign WITH CHECK
ADD CONSTRAINT FK_PlayersID FOREIGN KEY(PlayersID) REFERENCES Players(PlayerID)
ON UPDATE CASCADE

GO
ALTER TABLE Leaders WITH CHECK
ADD CONSTRAINT FK_CommandID FOREIGN KEY(CommandID) REFERENCES Commanders(ID)
ON UPDATE CASCADE


